# 1.Print 'Hello HCIA'.

In [1]:
print ("Hello HCIA")

Hello HCIA


# 2.Define two variables and calculate their sum.

In [2]:
a = 2
b = 4
print (a+b)

6


# 3.Define a list and replicate in three different ways.

In [44]:
import random
import pylab
list1 = ["да","прибудет","с","тобой","Cила"]
for j in range(3):
    random.shuffle(list1)
    for i in list1:
       print (i)
    print (" ")

да
с
тобой
прибудет
Cила
 
тобой
да
с
Cила
прибудет
 
прибудет
тобой
да
с
Cила
 


# 4.Define two lists and merge them together.

In [47]:
list1 = [1,2,3]
list2 = [6,0,7]
list3 = list1 + list2
print (list3)

[1, 2, 3, 6, 0, 7]


# 5. Get the last element of the list and print it.

In [49]:
list1 = [1,2,3]
print (list1[2])

3


# 6.Define a tuple that contains only one element.

In [50]:
c = (67)
print (c)

67


# 7.Define a three-line long string.

In [58]:
st = '''Hello world
Hello MTUCI
Hello comp
'''
print(st)

Hello world
Hello MTUCI
Hello comp



# 8.Define a tuple and then use the 'for loop' to print all the elements.

In [63]:
c = (1,2,3)
for i in range(3):
    print (c[i])

1
2
3


# 9.Define a function to do Multiplication, such as Mul(8,6),and its output 48.

In [71]:
def Mul(x,y):
    return x*y
Mul(51,2)    

102

# 10.Import numpy and use numpy to define an array, the its shape  is (5,5) and all its elements is 0.

In [73]:
import numpy
numpy.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# 11.Import numpy and use numpy to define an array, the shape is (4,6) and all elements is 0.

In [74]:
import numpy
numpy.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

# 12.Use numpy.arrange() to generate an array of shape(15,), then modify the shape to(3,5).

In [88]:
import numpy
Arr1 = numpy.arange(15.)
Arr2 = numpy.zeros((3,5))
Arr1 = Arr1.reshape(Arr2.shape)
print(Arr1)


[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]]


# 13.Define two matrices, then calculate and print the result of their point multiplication.

In [21]:
import numpy
Arr1 = numpy.arange(15.)
Arre = numpy.zeros((3,5))
Arr1 = Arr1.reshape(Arre.shape)
print(Arr1)
Arr2 = numpy.arange(15.)
Arre = numpy.zeros((3,5))
Arr2 = Arr2.reshape(Arre.shape)
print(Arr2)
print(Arr1*Arr2)

[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]]
[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]]
[[  0.   1.   4.   9.  16.]
 [ 25.  36.  49.  64.  81.]
 [100. 121. 144. 169. 196.]]
